runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:

# root
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.+)
  static_files: build/\1
  upload: build/.*

# We typically want to skip everything the "build" directory.
# Make sure to add a build script that removes source file maps.
# See:
#
#   https://github.com/facebookincubator/create-react-app/issues/1341#issuecomment-309689095
#
skip_files:
- ^(?!build).*$
