runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:

# root
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.+)
  static_files: build/\1
  upload: build/.*

# Don't include any client files
skip_files:
-  ^(.*/)?.*/node_modules/.*$
-  ^(.*/)?.*/src/.*$
